### ISSUE TITLE
Mysterious vendor not recognised since latest patch

### ISSUE THREAD

**Issue by suliamru100** [fabian57fabian/archero_bot_57#10]
**Describe the bug**
Thank you so much for your awesome work and effort you put into the archero bot. Unfortunately since the latest update(archero 1.4.4), the bot doesnt recognise the mysterious vendor that appears in cave stage. It reaches max loops and closes down. I wondered if you could please help me.

**Hardware description**
My phone is sony xperia xz3.

My screen resolution is 1440x2880.

My computer OS is windows.

**Screenshots*
I sent a zip with screenshoots to your yahoo mail, that tries to replicate the folder 1080x2220.  I hope it is okey?

**Comment by fabian57fabian** [comment]
Thank you for the contribution.
I received the screens. This week i'll add the resolutions and check the coordinates.
In the maintime could you download again the repo and use the Nox emulator?

**Comment by craftpiwurzel** [comment]
Can't you just change the screen resolution in the settings? That's how I did it. 
After that, everything worked.

**Comment by fabian57fabian** [comment]
There are a fixed set of resolutions supported for smartphone connection, but if you use the Nox emulator set to 1080x1920, it will surely work.
@craftpiwurzel Could you define "change the screen resolution in the settings" because as i've seen, on smartphones only a few resolutions are allowed (like HD, FHD, QWHD) so that particular resolution have to have coordinates checked.
Main problem of resolutions: **the game does not stretch when screen size is bigger**. So i have to manually change,
In future versions this will not be a problem since i'll introduce an AI screen state detector that doesn't rely on coordinates.
Ending conclusion: just copying the 1080x2280 folder into 1080x2288 won't simply work.

**Comment by suliamru100** [comment]
Thank you! i will use the emulator until then =)

@craftpiwurzel I am also curious over which setting you are refering to ?=O

**Comment by craftpiwurzel** [comment]
Yes I mean the one where you can choose between HD, FHD, QWHD. With me it works when I set it to FHD.
But if you have a different proportion, of course it can't anything.

**Comment by fabian57fabian** [comment]
It works because you have either 1920, 2220, 2280 2340 as height in your current resolution. He has a different one so it will not work. For now

**Comment by fabian57fabian** [comment]
Solved last commits edd8284f483b5b630905445c2bf6445fe262f44e with screens, coordinates and bug solved. This issue thread will be closed due to no other comments given
