### ISSUE TITLE
Stuttersteping

### ISSUE THREAD

**Issue by Lethtel** [fabian57fabian/archero_bot_57#14]
Hi,

For increasing sucessrate, we could get tougher or deadlier.
Both can be done by equipmnt upgrading, but the later  can also be done using stuttersteping (around +20~30% atk spd)

Can you add-it plz ?

If you want to centralise all info in the graphic interface, you could make a new box like the level one to let us choose our weapon, each weapon will be associated to a "stutterspeed"

If not, a simple editable file to get data from in which we could put our weapon's name

for example :
staff is 1.15x base atk spd
stutterspeed may be : 0.3s (meaning the bot will wait 0.3s before taping the screen again)

Base speed :
Bow : 1.00
Death Scythe : 0.85
Bright spear : 0.95
Stalker staff : 1.15
Tornado : 1.00
Saw blade : 1.50

I guess with spear (0.95x atk spd) it should be somewhere around 0.36s (will do some testing tomorrow, i'm out of energy)

It could be added after "Checking screen..."
If "In game. Playing but level not ended" => Stutterstep untill next step of the "checking screen" loop.
A good place for taping the screen would be near the center of the direction cross, somewhere close to "close_end" location as there is no other buttons at this place if i'm not wrong.

Tell me your thought ;)

**Comment by fabian57fabian** [comment]
Hello @Lethtel 
Sorry for replying so late.
Stutterstep is a perfect strategy to increase fire speed and was one of the first things i tried as a gamer and developer.

Unfortunately the adb package allow us to ask for a tap, swipe, and some other things but it is slow and besides that, once send the command, current task is blocked until an 'OK' answer is received (in other words, asb shell input commands are sync). Besides that it is slow and different phones and emulators have different answer time.
This means that trying a stutterstep strategy will be inpossible because doing the movement exactly when an attack was just released (in order to cut down the ending atk time) is not impossible but really difficult.
A timer, a checked timer, a timer with secondary threads are not enough to do this feature (i tried it out for 2 days after calling it a dead feature).

For people who don't know what stutterstep is, check out this video from another game:
https://www.youtube.com/watch?v=OW-X9SDBrpA

**Comment by fabian57fabian** [comment]
Keeping this issue open another 4 days for optional advices, then i'll close it
