### ISSUE TITLE
Nox Emulator Running on Instance 0

### ISSUE THREAD

**Issue by vanceyx** [fabian57fabian/archero_bot_57#16]
Hi, i would like to know if its possible that i can edit to let the program run Nox other instances rather than only default 0. device wont be detected if i run other instances like 1 or 2 etc.

Thank you!

**Comment by fabian57fabian** [comment]
Hello there,If you open multiple nox emulators i think each one will open a different socket (a couple ip and port). Normally ip is localhost (127.0.0.1) and port is 62001.Try changing the UsbConnector.py script at line 75.5037 is for usb phone connected, 62001 is for default nox.I'll soon add a new setting in order to change it from interface

Inviato da Yahoo Mail su Android 
 
  Il Mar, 14 Lug, 2020 alle 15:55, vanceyx<notifications@github.com> ha scritto:   


Hi, i would like to know if its possible that i can edit to let the program run Nox other instances rather than only default 0. device wont be detected if i run other instances like 1 or 2 etc.

Thank you!

**Comment by vanceyx** [comment]
Thanks you very much, i will try it.

**Comment by vanceyx** [comment]
Hi Fabian, may i know why if i open another nox emulator instance (not no.0) , the bot still wont work, i can only open 1 archero instance? Would like to play other games while botting.

**Comment by fabian57fabian** [comment]
Hello. If openning a new Nox instance means that last port of nox instance is changed, then of course it will fail.

Have to test this manually, for now it is a feature that i will not add. Closing.
