### ISSUE TITLE
Stuck at Level 18

### ISSUE THREAD

**Issue by vanceyx** [fabian57fabian/archero_bot_57#18]
Hi,

Im always stucked at level 18 top right corner. Is there anyway to fix this?

Thank you.
VanCe

**Comment by vanceyx** [comment]
Hi,

Does anyone knows where to edit the codes for movements? i looked around Designfor#6 part but to no avail.

**Comment by wharrus** [comment]
im getting the same issue . stuck at 18

**Comment by kilolum** [comment]
which resolution are u guys using? im using 1080x1920 and i found that it gets stuck for me too sometimes at level 18. it happens when i get more xp then usual and reach max rank. in my language the message "Level max in this adventure" in the yellow bar is very long and one of the coordinates that get checked have a different color then expected cause of the shadow of the text. --> didnt recognise the level up state and was stuck in "unknown". I moved the coordinate of the checked pixel a little bit to the left and checked with the TouchManager if it gets the correct color now at the new location. 
if you want to change it go to datas/1080x1920/coords/static_coords.json.

for me it was the first pixel that was detected wrong. but it can be different in your language. 

my change was
"select_ability":{
        "coordinates": [[0.06851851851851851, 0.19538461538461538],

but better check the TouchManager with a screenshot of yours. (If you even get the error that u land in an unknown state)....

**Comment by fabian57fabian** [comment]
Thanks @kilolum for the manual check of this problem.

Indeed i never taught about max level reached.

If anyone could take a screenshot in that situation, it would be a lot.

Anyone can add a screenshot in the datas/1080x1920/screens folder and the execute the check_static_coords.py

I will manually try to test this bug.

Btw i checked the new updates, added new screenshots, solved some internal bugs within commit edd8284f483b5b630905445c2bf6445fe262f44e.

**Comment by fabian57fabian** [comment]
After last commits and newest tests, it is not stopping anymore at level 18.
Sometimes it may happen to not go forward, but it heavly depends on machine capability.
Nox uses 2-4 cores and renders a FullHD image, so when sending a swipe movement, it may be slow, or end before.
I did specify the rwuirements in Readme and there is a need for a mid-level pc/laètop that can run nox without lags.
Those lags are out of this project goal.

Closing the issue, feel free to open it again if newer problems arise.
