### ISSUE TITLE
GAmeCOntroller not workin

### ISSUE THREAD

**Issue by crunher** [fabian57fabian/archero_bot_57#21]
**Describe the bug**
When I try to start the gamecontroller nothing happens

https://user-images.githubusercontent.com/22467254/106390853-aebc3880-63ea-11eb-8b7d-04a5be735dde.mp4

**Comment by fabian57fabian** [comment]
Hello @crunher when executing python scripts (files ending with .py) you normally launch from the console, but you can double click.

The trouble is that, if you launch (double click) the program and it outputs an error, you will see nothing because the console will close immediately.

Try opening a command line in your folder (in your folder, in the navigation bar, type **CMD**), then a console will open up. Now type **python GameController.py**. It will show you an error. Please post it

**Comment by fabian57fabian** [comment]
GameController was tested with 1080x1920 resolution using nox and it works witrh commit edd8284f483b5b630905445c2bf6445fe262f44e

Even with 2 cores and low speed.
