### ISSUE TITLE
Save screenshot of the loot

### ISSUE THREAD

**Issue by craftpiwurzel** [fabian57fabian/archero_bot_57#9]
**Is your feature request related to a problem? Please describe.**
Save the screenshot of the loot.

**Describe the solution you'd like**
First of all really cool and good bot.
I have one(two) feature request.
1. Is it possible that it saves the screenshot from the end in a folder.(endgame.png)
Then you can check later what and how much he has farmed.
2. The second one was already requested, that you can also choose chapter 3 for farm

**Comment by fabian57fabian** [comment]
Thank you. As for your questions:
1. Basic statistics are saved in a csv file. You can view statistics for winned games and reached levels by opening the script "PlotStatistics"
2. Chapter 3 and 11 are under progress and testing, so they'll come out soon.
I will close this issue when i'll finish chapter 3 feature.

**Comment by fabian57fabian** [comment]
With last commit i added Dungeons 3, 6, 10.
Click the image and select the dungeon you want to play.
Closing issue because of feature/s correctly added.

**Comment by Lethtel** [comment]
Nice way to track in a simple view, but i would prefer screenshots if possible.
2 reasons : 
- Sometime due to OOS or bugs, stats are messed up.
- Most important one from my point of view :
   CSV files do not take in count loot (Gold earned but mostly drops) which may be usefull for discord archero community who are trying to gather data (see google form : https://forms.gle/tyY85zvetXp1Li1E6 ; and results : https://docs.google.com/spreadsheets/d/1ucNHWsgtdmrGsDqkM36liYnhBBwmMc5baBncobQDEAc/edit?usp=sharing)
Knowing that they are working on a way to OCR screens.

If possible, completed runs should get named differently as only completed runs should be reported to get good stats

**Comment by fabian57fabian** [comment]
Hello,Chapter 3 can be choosed but it is under tests (can't reach ending of all dungeons).As for loot screenshots, cool idea. I'll add it.

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 22, 2020 at 12:33, craftpiwurzel<notifications@github.com> wrote:   


Is your feature request related to a problem? Please describe.
Save the screenshot of the loot.

Describe the solution you'd like
First of all really cool and good bot.
I have one(two) feature request.
   
   - Is it possible that it saves the screenshot from the end in a folder.(endgame.png)   
Then you can check later what and how much he has farmed.
   - The second one was already requested, that you can also choose chapter 3 for farm
